apiVersion: apps/v1
kind: Deployment
metadata:
  name: proyecto-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proyecto-app
  template:
    metadata:
      labels:
        app: proyecto-app
    spec:
      containers:
        - name: app
          image: 582687411664.dkr.ecr.us-east-2.amazonaws.com/proyecto:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: proyecto-app
spec:
  selector:
    app: proyecto-app
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer